# https://tekton.dev/docs/triggers/triggerbindings/
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: basic-pipeline-binding
spec: 
  params:
    - name: branch
      value: "main"